// Mocks generated by Mockito 5.4.6 from annotations
// in the_borrowed_wings/test/igc_writer_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:mockito/mockito.dart' as _i1;
import 'package:supabase_flutter/supabase_flutter.dart' as _i11;
import 'package:the_borrowed_wings/models/flight.dart' as _i2;
import 'package:the_borrowed_wings/models/flight_fix.dart' as _i3;
import 'package:the_borrowed_wings/models/glider.dart' as _i5;
import 'package:the_borrowed_wings/models/pilot.dart' as _i4;
import 'package:the_borrowed_wings/repositories/flight_repository.dart' as _i7;
import 'package:the_borrowed_wings/repositories/glider_repository.dart' as _i10;
import 'package:the_borrowed_wings/repositories/pilot_repository.dart' as _i9;
import 'package:the_borrowed_wings/services/auth_service.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFlight_0 extends _i1.SmartFake implements _i2.Flight {
  _FakeFlight_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFlightFix_1 extends _i1.SmartFake implements _i3.FlightFix {
  _FakeFlightFix_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePilot_2 extends _i1.SmartFake implements _i4.Pilot {
  _FakePilot_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGlider_3 extends _i1.SmartFake implements _i5.Glider {
  _FakeGlider_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthResult_4 extends _i1.SmartFake implements _i6.AuthResult {
  _FakeAuthResult_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FlightRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlightRepository extends _i1.Mock implements _i7.FlightRepository {
  MockFlightRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i2.Flight> createFlight(_i2.Flight? flight) =>
      (super.noSuchMethod(
            Invocation.method(#createFlight, [flight]),
            returnValue: _i8.Future<_i2.Flight>.value(
              _FakeFlight_0(this, Invocation.method(#createFlight, [flight])),
            ),
          )
          as _i8.Future<_i2.Flight>);

  @override
  _i8.Future<_i2.Flight> updateFlight(_i2.Flight? flight, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#updateFlight, [flight, userId]),
            returnValue: _i8.Future<_i2.Flight>.value(
              _FakeFlight_0(
                this,
                Invocation.method(#updateFlight, [flight, userId]),
              ),
            ),
          )
          as _i8.Future<_i2.Flight>);

  @override
  _i8.Future<List<Map<String, dynamic>>> getFlightsWithGlidersByUserId(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getFlightsWithGlidersByUserId, [userId]),
            returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i8.Future<List<Map<String, dynamic>>>);

  @override
  _i8.Future<_i2.Flight?> getFlightById(String? id, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getFlightById, [id, userId]),
            returnValue: _i8.Future<_i2.Flight?>.value(),
          )
          as _i8.Future<_i2.Flight?>);

  @override
  _i8.Future<List<_i2.Flight>> getFlightsByGliderId(
    String? gliderId,
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getFlightsByGliderId, [gliderId, userId]),
            returnValue: _i8.Future<List<_i2.Flight>>.value(<_i2.Flight>[]),
          )
          as _i8.Future<List<_i2.Flight>>);

  @override
  _i8.Future<void> deleteFlight(String? id, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFlight, [id, userId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<int> getFlightCountByUserId(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getFlightCountByUserId, [userId]),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<_i3.FlightFix> addFlightFix(_i3.FlightFix? fix) =>
      (super.noSuchMethod(
            Invocation.method(#addFlightFix, [fix]),
            returnValue: _i8.Future<_i3.FlightFix>.value(
              _FakeFlightFix_1(this, Invocation.method(#addFlightFix, [fix])),
            ),
          )
          as _i8.Future<_i3.FlightFix>);

  @override
  _i8.Future<List<_i3.FlightFix>> addFlightFixesBatch(
    List<_i3.FlightFix>? fixes,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addFlightFixesBatch, [fixes]),
            returnValue: _i8.Future<List<_i3.FlightFix>>.value(
              <_i3.FlightFix>[],
            ),
          )
          as _i8.Future<List<_i3.FlightFix>>);

  @override
  _i8.Future<List<_i3.FlightFix>> getFlightFixesByFlightId(String? flightId) =>
      (super.noSuchMethod(
            Invocation.method(#getFlightFixesByFlightId, [flightId]),
            returnValue: _i8.Future<List<_i3.FlightFix>>.value(
              <_i3.FlightFix>[],
            ),
          )
          as _i8.Future<List<_i3.FlightFix>>);

  @override
  _i8.Future<List<_i3.FlightFix>> getFlightFixesInRange(
    String? flightId,
    int? startSeq,
    int? endSeq,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getFlightFixesInRange, [
              flightId,
              startSeq,
              endSeq,
            ]),
            returnValue: _i8.Future<List<_i3.FlightFix>>.value(
              <_i3.FlightFix>[],
            ),
          )
          as _i8.Future<List<_i3.FlightFix>>);

  @override
  _i8.Future<_i3.FlightFix?> getLatestFlightFix(String? flightId) =>
      (super.noSuchMethod(
            Invocation.method(#getLatestFlightFix, [flightId]),
            returnValue: _i8.Future<_i3.FlightFix?>.value(),
          )
          as _i8.Future<_i3.FlightFix?>);

  @override
  _i8.Future<Map<String, dynamic>> getFlightStatsByUserId(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getFlightStatsByUserId, [userId]),
            returnValue: _i8.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<void> deleteAllFlightsByUserId(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAllFlightsByUserId, [userId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}

/// A class which mocks [PilotRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPilotRepository extends _i1.Mock implements _i9.PilotRepository {
  MockPilotRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i4.Pilot> createPilot(_i4.Pilot? pilot) =>
      (super.noSuchMethod(
            Invocation.method(#createPilot, [pilot]),
            returnValue: _i8.Future<_i4.Pilot>.value(
              _FakePilot_2(this, Invocation.method(#createPilot, [pilot])),
            ),
          )
          as _i8.Future<_i4.Pilot>);

  @override
  _i8.Future<_i4.Pilot?> getPilotByUserId(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getPilotByUserId, [userId]),
            returnValue: _i8.Future<_i4.Pilot?>.value(),
          )
          as _i8.Future<_i4.Pilot?>);

  @override
  _i8.Future<_i4.Pilot?> getPilotById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getPilotById, [id]),
            returnValue: _i8.Future<_i4.Pilot?>.value(),
          )
          as _i8.Future<_i4.Pilot?>);

  @override
  _i8.Future<_i4.Pilot> updatePilot(_i4.Pilot? pilot) =>
      (super.noSuchMethod(
            Invocation.method(#updatePilot, [pilot]),
            returnValue: _i8.Future<_i4.Pilot>.value(
              _FakePilot_2(this, Invocation.method(#updatePilot, [pilot])),
            ),
          )
          as _i8.Future<_i4.Pilot>);

  @override
  _i8.Future<_i4.Pilot> updatePilotByUserId(String? userId, _i4.Pilot? pilot) =>
      (super.noSuchMethod(
            Invocation.method(#updatePilotByUserId, [userId, pilot]),
            returnValue: _i8.Future<_i4.Pilot>.value(
              _FakePilot_2(
                this,
                Invocation.method(#updatePilotByUserId, [userId, pilot]),
              ),
            ),
          )
          as _i8.Future<_i4.Pilot>);

  @override
  _i8.Future<bool> hasPilotProfile(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#hasPilotProfile, [userId]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<void> deletePilot(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deletePilot, [id]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<_i4.Pilot>> getAllPilots() =>
      (super.noSuchMethod(
            Invocation.method(#getAllPilots, []),
            returnValue: _i8.Future<List<_i4.Pilot>>.value(<_i4.Pilot>[]),
          )
          as _i8.Future<List<_i4.Pilot>>);
}

/// A class which mocks [GliderRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGliderRepository extends _i1.Mock implements _i10.GliderRepository {
  MockGliderRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i5.Glider> createGlider(_i5.Glider? glider) =>
      (super.noSuchMethod(
            Invocation.method(#createGlider, [glider]),
            returnValue: _i8.Future<_i5.Glider>.value(
              _FakeGlider_3(this, Invocation.method(#createGlider, [glider])),
            ),
          )
          as _i8.Future<_i5.Glider>);

  @override
  _i8.Future<List<_i5.Glider>> getGlidersByUserId(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getGlidersByUserId, [userId]),
            returnValue: _i8.Future<List<_i5.Glider>>.value(<_i5.Glider>[]),
          )
          as _i8.Future<List<_i5.Glider>>);

  @override
  _i8.Future<_i5.Glider?> getGliderById(String? id, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getGliderById, [id, userId]),
            returnValue: _i8.Future<_i5.Glider?>.value(),
          )
          as _i8.Future<_i5.Glider?>);

  @override
  _i8.Future<_i5.Glider> updateGlider(_i5.Glider? glider, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#updateGlider, [glider, userId]),
            returnValue: _i8.Future<_i5.Glider>.value(
              _FakeGlider_3(
                this,
                Invocation.method(#updateGlider, [glider, userId]),
              ),
            ),
          )
          as _i8.Future<_i5.Glider>);

  @override
  _i8.Future<void> deleteGlider(String? id, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteGlider, [id, userId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<int> getGliderCountByUserId(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getGliderCountByUserId, [userId]),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<bool> hasGliders(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#hasGliders, [userId]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<List<_i5.Glider>> searchGlidersByModel(
    String? userId,
    String? modelQuery,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchGlidersByModel, [userId, modelQuery]),
            returnValue: _i8.Future<List<_i5.Glider>>.value(<_i5.Glider>[]),
          )
          as _i8.Future<List<_i5.Glider>>);

  @override
  _i8.Future<List<_i5.Glider>> getGlidersByManufacturer(
    String? userId,
    String? manufacturer,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getGlidersByManufacturer, [
              userId,
              manufacturer,
            ]),
            returnValue: _i8.Future<List<_i5.Glider>>.value(<_i5.Glider>[]),
          )
          as _i8.Future<List<_i5.Glider>>);

  @override
  _i8.Future<void> deleteAllGlidersByUserId(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAllGlidersByUserId, [userId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i6.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Stream<_i11.AuthState> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i8.Stream<_i11.AuthState>.empty(),
          )
          as _i8.Stream<_i11.AuthState>);

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  _i8.Future<_i6.AuthResult> signUp({
    required String? email,
    required String? password,
    required String? fullName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [], {
              #email: email,
              #password: password,
              #fullName: fullName,
            }),
            returnValue: _i8.Future<_i6.AuthResult>.value(
              _FakeAuthResult_4(
                this,
                Invocation.method(#signUp, [], {
                  #email: email,
                  #password: password,
                  #fullName: fullName,
                }),
              ),
            ),
          )
          as _i8.Future<_i6.AuthResult>);

  @override
  _i8.Future<_i6.AuthResult> signIn({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i8.Future<_i6.AuthResult>.value(
              _FakeAuthResult_4(
                this,
                Invocation.method(#signIn, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i8.Future<_i6.AuthResult>);

  @override
  _i8.Future<_i6.AuthResult> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i8.Future<_i6.AuthResult>.value(
              _FakeAuthResult_4(this, Invocation.method(#signOut, [])),
            ),
          )
          as _i8.Future<_i6.AuthResult>);

  @override
  _i8.Future<_i6.AuthResult> resetPassword({required String? email}) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [], {#email: email}),
            returnValue: _i8.Future<_i6.AuthResult>.value(
              _FakeAuthResult_4(
                this,
                Invocation.method(#resetPassword, [], {#email: email}),
              ),
            ),
          )
          as _i8.Future<_i6.AuthResult>);

  @override
  _i8.Future<_i6.AuthResult> updatePassword({required String? newPassword}) =>
      (super.noSuchMethod(
            Invocation.method(#updatePassword, [], {#newPassword: newPassword}),
            returnValue: _i8.Future<_i6.AuthResult>.value(
              _FakeAuthResult_4(
                this,
                Invocation.method(#updatePassword, [], {
                  #newPassword: newPassword,
                }),
              ),
            ),
          )
          as _i8.Future<_i6.AuthResult>);

  @override
  _i8.Future<_i6.AuthResult> updateProfile({String? fullName, String? email}) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {
              #fullName: fullName,
              #email: email,
            }),
            returnValue: _i8.Future<_i6.AuthResult>.value(
              _FakeAuthResult_4(
                this,
                Invocation.method(#updateProfile, [], {
                  #fullName: fullName,
                  #email: email,
                }),
              ),
            ),
          )
          as _i8.Future<_i6.AuthResult>);
}
