import 'dart:convert';
import 'dart:io';
import 'package:path/path.dart' as path;
import 'package:path_provider/path_provider.dart';
import '../models/flight.dart';
import '../models/flight_fix.dart';
import '../models/glider.dart';
import '../models/pilot.dart';
import '../db/flight_dao.dart';
import '../db/pilot_dao.dart';
import 'igc_utils.dart';

/// Result of IGC export operation
class IgcExportResult {
  final bool success;
  final String? filePath;
  final String? error;
  final int? fixCount;

  const IgcExportResult({
    required this.success,
    this.filePath,
    this.error,
    this.fixCount,
  });

  factory IgcExportResult.success(String filePath, int fixCount) {
    return IgcExportResult(
      success: true,
      filePath: filePath,
      fixCount: fixCount,
    );
  }

  factory IgcExportResult.error(String error) {
    return IgcExportResult(
      success: false,
      error: error,
    );
  }
}

/// IGC file writer for exporting flights to aviation standard format.
/// 
/// Generates IGC files with proper headers, GPS fixes, and metadata
/// according to IGC specification for flight data exchange.
class IgcWriter {
  final FlightDao _flightDao;
  final PilotDao _pilotDao;
  final String? _testOutputDir; // For testing purposes

  IgcWriter({
    FlightDao? flightDao,
    PilotDao? pilotDao,
    String? testOutputDir,
  }) : _flightDao = flightDao ?? FlightDao(),
       _pilotDao = pilotDao ?? PilotDao(),
       _testOutputDir = testOutputDir;

  /// Export a complete flight to IGC format
  Future<IgcExportResult> exportFlight(int flightId) async {
    try {
      // Get flight with glider information
      final flightWithGlider = await _flightDao.getFlightWithGlider(flightId);
      if (flightWithGlider == null) {
        return IgcExportResult.error('Flight not found');
      }

      final flight = flightWithGlider['flight'] as Flight;
      final glider = flightWithGlider['glider'] as Glider;

      // Get pilot information
      final pilot = await _pilotDao.getProfile();

      // Get flight fixes (only between takeoff and landing if available)
      List<FlightFix> fixes;
      if (flight.takeoffAt != null && flight.landedAt != null) {
        fixes = await _flightDao.getFlightFixesInTimeRange(
          flightId,
          flight.takeoffAt!,
          flight.landedAt!,
        );
      } else {
        fixes = await _flightDao.getFlightFixes(flightId);
      }

      if (fixes.isEmpty) {
        return IgcExportResult.error('No flight fixes to export');
      }

      // Generate IGC content
      final igcContent = await _generateIgcContent(flight, glider, pilot, fixes);

      // Write to file
      final filePath = await _writeIgcFile(flight, glider, igcContent);

      // Update flight record with IGC path
      await _flightDao.updateFlightIgcPath(flightId, filePath);

      return IgcExportResult.success(filePath, fixes.length);
    } catch (e) {
      return IgcExportResult.error('Export failed: $e');
    }
  }

  /// Generate IGC file content from flight data
  Future<String> _generateIgcContent(
    Flight flight,
    Glider glider,
    Pilot? pilot,
    List<FlightFix> fixes,
  ) async {
    final lines = <String>[];

    // A record - manufacturer and logger ID (required first line)
    lines.add(IgcUtils.generateARecord());

    // H records - header information
    lines.add(IgcUtils.generateDateHeader(flight.startedAt));
    
    if (pilot != null && pilot.fullName.isNotEmpty) {
      lines.add(IgcUtils.generatePilotHeader(pilot.fullName));
    } else {
      lines.add('HFPLTPILOTINCHARGE:Unknown');
    }

    lines.add(IgcUtils.generateGliderTypeHeader(
      glider.manufacturer ?? '',
      glider.model,
    ));

    lines.add(IgcUtils.generateGliderIdHeader(glider.gliderId));
    lines.add(IgcUtils.generateGpsDatumHeader());
    lines.add(IgcUtils.generateFirmwareHeader());

    // Additional headers
    lines.add('HFSITSITE:${_generateSiteInfo(fixes)}');
    lines.add('HFCCLCOMPETITIONCLASS:${glider.wingClass ?? ''}');
    
    // L records - comments with app-specific metadata
    lines.add(IgcUtils.generateComment('Generated by ParaglidingLog Flutter App'));
    lines.add(IgcUtils.generateComment('Flight ID: ${flight.id}'));
    lines.add(IgcUtils.generateComment('Recording Duration: ${flight.formattedRecordingDuration}'));
    if (flight.isCompleted) {
      lines.add(IgcUtils.generateComment('Flight Duration: ${flight.formattedFlightDuration}'));
    }
    lines.add(IgcUtils.generateComment('Total Fixes: ${fixes.length}'));

    // B records - GPS fixes (the main flight track data)
    for (final fix in fixes) {
      final bRecord = IgcUtils.generateBRecord(
        fix.timestamp,
        fix.latitude,
        fix.longitude,
        fix.pressureAltitudeM,
        fix.gpsAltitudeM,
      );
      lines.add(bRecord);
    }

    return lines.join('\r\n');
  }

  /// Generate site information from first fix
  String _generateSiteInfo(List<FlightFix> fixes) {
    if (fixes.isEmpty) return 'Unknown';
    
    final firstFix = fixes.first;
    final lat = firstFix.latitude.toStringAsFixed(4);
    final lon = firstFix.longitude.toStringAsFixed(4);
    
    return 'Takeoff: $lat, $lon';
  }

  /// Write IGC content to file in app documents directory
  Future<String> _writeIgcFile(Flight flight, Glider glider, String content) async {
    final Directory baseDirectory;
    if (_testOutputDir != null) {
      baseDirectory = Directory(_testOutputDir!);
    } else {
      baseDirectory = await getApplicationDocumentsDirectory();
    }
    
    final igcDir = Directory(path.join(baseDirectory.path, 'igc_exports'));
    
    // Create directory if it doesn't exist
    if (!await igcDir.exists()) {
      await igcDir.create(recursive: true);
    }

    // Generate filename
    final filename = IgcUtils.generateIgcFilename(flight.startedAt, glider.model);
    final filePath = path.join(igcDir.path, filename);

    // Write file
    final file = File(filePath);
    await file.writeAsString(content, encoding: utf8);

    return filePath;
  }

  /// Export flight and return file for sharing
  Future<File?> exportFlightForSharing(int flightId) async {
    final result = await exportFlight(flightId);
    if (result.success && result.filePath != null) {
      return File(result.filePath!);
    }
    return null;
  }

  /// Get IGC file path for existing export
  Future<String?> getExistingIgcPath(int flightId) async {
    final flight = await _flightDao.getFlightById(flightId);
    return flight?.igcPath;
  }

  /// Check if IGC file exists for flight
  Future<bool> hasIgcExport(int flightId) async {
    final igcPath = await getExistingIgcPath(flightId);
    if (igcPath == null) return false;
    
    final file = File(igcPath);
    return await file.exists();
  }

  /// Delete IGC export file
  Future<bool> deleteIgcExport(int flightId) async {
    try {
      final igcPath = await getExistingIgcPath(flightId);
      if (igcPath == null) return true;
      
      final file = File(igcPath);
      if (await file.exists()) {
        await file.delete();
      }
      
      // Clear IGC path from database
      await _flightDao.updateFlightIgcPath(flightId, '');
      return true;
    } catch (e) {
      return false;
    }
  }

  /// Validate IGC file format
  static bool validateIgcContent(String content) {
    final lines = content.split('\n');
    if (lines.isEmpty) return false;

    // Check for required A record at start
    if (!lines.first.startsWith('A')) {
      return false;
    }

    // Check for required date header
    bool hasDateHeader = false;
    bool hasBRecords = false;

    for (final line in lines) {
      final trimmedLine = line.trim();
      if (trimmedLine.startsWith('HFDTE')) {
        hasDateHeader = true;
      } else if (trimmedLine.startsWith('B')) {
        hasBRecords = true;
        
        // Validate B record format
        if (trimmedLine.length < 35) {
          return false;
        }
      }
    }

    return hasDateHeader && hasBRecords;
  }

  /// Get IGC file statistics
  Future<Map<String, dynamic>?> getIgcFileStats(String filePath) async {
    try {
      final file = File(filePath);
      if (!await file.exists()) return null;

      final content = await file.readAsString();
      final lines = content.split('\n');
      
      int bRecordCount = 0;
      String? flightDate;
      
      for (final line in lines) {
        final trimmedLine = line.trim();
        if (trimmedLine.startsWith('B')) {
          bRecordCount++;
        } else if (trimmedLine.startsWith('HFDTE')) {
          flightDate = trimmedLine.substring(5);
        }
      }

      final fileSize = await file.length();
      
      return {
        'file_size_bytes': fileSize,
        'line_count': lines.length,
        'b_record_count': bRecordCount,
        'flight_date': flightDate,
        'is_valid': validateIgcContent(content),
      };
    } catch (e) {
      return null;
    }
  }

  /// Clean up old IGC exports (optional maintenance)
  Future<int> cleanupOldExports({int maxAgeDays = 90}) async {
    try {
      final Directory baseDirectory;
      if (_testOutputDir != null) {
        baseDirectory = Directory(_testOutputDir!);
      } else {
        baseDirectory = await getApplicationDocumentsDirectory();
      }
      
      final igcDir = Directory(path.join(baseDirectory.path, 'igc_exports'));
      
      if (!await igcDir.exists()) return 0;

      final cutoffDate = DateTime.now().subtract(Duration(days: maxAgeDays));
      int deletedCount = 0;

      await for (final entity in igcDir.list()) {
        if (entity is File && entity.path.endsWith('.igc')) {
          final stat = await entity.stat();
          if (stat.modified.isBefore(cutoffDate)) {
            await entity.delete();
            deletedCount++;
          }
        }
      }

      return deletedCount;
    } catch (e) {
      return 0;
    }
  }
}